version: 1.3.4

cache: false

interface:
  privacyPolicy:
    externalUrl: "https://librechat.ai/privacy-policy"
    openNewTab: true
  termsOfService:
    externalUrl: "https://librechat.ai/tos"
    openNewTab: true

endpoints:
  agents:
    recursionLimit: 50
    maxRecursionLimit: 100
    disableBuilder: false
  custom:
    - name: "EU Privacy LLMs"
      apiKey: "${EU_PRIVACY_LLMS_API_KEY}"
      baseURL: "${EU_PRIVACY_LLMS_BASEURL}"
      models:
        default:
          - "qwen3.5-397b-a17b"
      addParams:
        preference: "balanced"
      titleConvo: true
      titleModel: "qwen3.5-397b-a17b"
      summarize: true
      summaryModel: "qwen3.5-397b-a17b"
      modelDisplayLabel: "Qwen3.5"

speech:
  stt:
    azureOpenAI:
      instanceName: "${AZURE_OPENAI_INSTANCE_NAME}"
      apiKey: "${AZURE_OPENAI_API_KEY}"
      deploymentName: "${AZURE_OPENAI_WHISPER_DEPLOYMENT_NAME}"
      apiVersion: "2024-02-01"
  speechTab:
    speechToText:
      engineSTT: azureOpenAI
      languageSTT: "de-DE"
      autoTranscribeAudio: false
      decibelValue: -45
      autoSendText: -1
